object Versions {
    const val mockk: String = "1.12.5"
    const val room = "2.4.2"
    const val daggerHilt = "2.44.2"
    const val hiltPath = "2.44.2"
    const val composeNavigation = "2.5.0-alpha03"
    const val espressoTest: String = "3.5.0"
    const val androidTest: String = "1.1.3"
    const val composeActivity = "1.6.1"
    const val lifeCycle = "2.4.1"
    const val androidCore = "1.9.0"
    const val gradlePlugin = "7.3.0"
    const val ktLintGradle = "10.0.0"
    const val ktLint = "0.34.2"
    const val kotlin = "1.7.10"
    const val appCompat = "1.5.1"
    const val jUnit = "4.13.2"
    const val compose = "1.3.1"
    const val retrofit = "2.6.2"
    const val retrofitCoroutines = "0.9.2"
    const val coroutinesTesting ="1.6.3"
    const val retrofitGson = "2.6.2"
    const val gson = "2.8.5"
    const val okHttp = "4.10.0"
    const val material_three = "1.1.0-alpha02"
    const val pager = "0.12.0"
    const val coreTesting ="2.1.0"
}
